// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTEyLG4MHGP3GeDSSyXMCq_0iycHGnL90',
    appId: '1:178835611993:web:13dc8024e79e2f02522c48',
    messagingSenderId: '178835611993',
    projectId: 'flutterauth-b4897',
    authDomain: 'flutterauth-b4897.firebaseapp.com',
    storageBucket: 'flutterauth-b4897.appspot.com',
    measurementId: 'G-M042RX5FP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrRqol4iGQvOXuOvpQ-eOhjoHLRZ8L1r4',
    appId: '1:178835611993:android:94443d02b12f991f522c48',
    messagingSenderId: '178835611993',
    projectId: 'flutterauth-b4897',
    storageBucket: 'flutterauth-b4897.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY1d095-_F73Biu0pf6KcDq7X04xNrMwg',
    appId: '1:178835611993:ios:b87ec7a4e5bd487a522c48',
    messagingSenderId: '178835611993',
    projectId: 'flutterauth-b4897',
    storageBucket: 'flutterauth-b4897.appspot.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY1d095-_F73Biu0pf6KcDq7X04xNrMwg',
    appId: '1:178835611993:ios:e2a1a6f8095a8155522c48',
    messagingSenderId: '178835611993',
    projectId: 'flutterauth-b4897',
    storageBucket: 'flutterauth-b4897.appspot.com',
    iosBundleId: 'com.example.flutterAuth.RunnerTests',
  );
}
